apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.name}}
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - merlin
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner}}
  # TODO: Fill in your system name here.
  # system:
  # TODO: Fill in the components and resources that this depends on
  # dependsOn:
  #  - component:upstream-component
